/* automatically generated by rust-bindgen 0.70.1 */

pub const AE_ENABLE: libcamera_controls__bindgen_ty_1 = 1;
pub const AE_STATE: libcamera_controls__bindgen_ty_1 = 2;
pub const AE_METERING_MODE: libcamera_controls__bindgen_ty_1 = 3;
pub const AE_CONSTRAINT_MODE: libcamera_controls__bindgen_ty_1 = 4;
pub const AE_EXPOSURE_MODE: libcamera_controls__bindgen_ty_1 = 5;
pub const EXPOSURE_VALUE: libcamera_controls__bindgen_ty_1 = 6;
pub const EXPOSURE_TIME: libcamera_controls__bindgen_ty_1 = 7;
pub const EXPOSURE_TIME_MODE: libcamera_controls__bindgen_ty_1 = 8;
pub const ANALOGUE_GAIN: libcamera_controls__bindgen_ty_1 = 9;
pub const ANALOGUE_GAIN_MODE: libcamera_controls__bindgen_ty_1 = 10;
pub const AE_FLICKER_MODE: libcamera_controls__bindgen_ty_1 = 11;
pub const AE_FLICKER_PERIOD: libcamera_controls__bindgen_ty_1 = 12;
pub const AE_FLICKER_DETECTED: libcamera_controls__bindgen_ty_1 = 13;
pub const BRIGHTNESS: libcamera_controls__bindgen_ty_1 = 14;
pub const CONTRAST: libcamera_controls__bindgen_ty_1 = 15;
pub const LUX: libcamera_controls__bindgen_ty_1 = 16;
pub const AWB_ENABLE: libcamera_controls__bindgen_ty_1 = 17;
pub const AWB_MODE: libcamera_controls__bindgen_ty_1 = 18;
pub const AWB_LOCKED: libcamera_controls__bindgen_ty_1 = 19;
pub const COLOUR_GAINS: libcamera_controls__bindgen_ty_1 = 20;
pub const COLOUR_TEMPERATURE: libcamera_controls__bindgen_ty_1 = 21;
pub const SATURATION: libcamera_controls__bindgen_ty_1 = 22;
pub const SENSOR_BLACK_LEVELS: libcamera_controls__bindgen_ty_1 = 23;
pub const SHARPNESS: libcamera_controls__bindgen_ty_1 = 24;
pub const FOCUS_FO_M: libcamera_controls__bindgen_ty_1 = 25;
pub const COLOUR_CORRECTION_MATRIX: libcamera_controls__bindgen_ty_1 = 26;
pub const SCALER_CROP: libcamera_controls__bindgen_ty_1 = 27;
pub const DIGITAL_GAIN: libcamera_controls__bindgen_ty_1 = 28;
pub const FRAME_DURATION: libcamera_controls__bindgen_ty_1 = 29;
pub const FRAME_DURATION_LIMITS: libcamera_controls__bindgen_ty_1 = 30;
pub const SENSOR_TEMPERATURE: libcamera_controls__bindgen_ty_1 = 31;
pub const SENSOR_TIMESTAMP: libcamera_controls__bindgen_ty_1 = 32;
pub const AF_MODE: libcamera_controls__bindgen_ty_1 = 33;
pub const AF_RANGE: libcamera_controls__bindgen_ty_1 = 34;
pub const AF_SPEED: libcamera_controls__bindgen_ty_1 = 35;
pub const AF_METERING: libcamera_controls__bindgen_ty_1 = 36;
pub const AF_WINDOWS: libcamera_controls__bindgen_ty_1 = 37;
pub const AF_TRIGGER: libcamera_controls__bindgen_ty_1 = 38;
pub const AF_PAUSE: libcamera_controls__bindgen_ty_1 = 39;
pub const LENS_POSITION: libcamera_controls__bindgen_ty_1 = 40;
pub const AF_STATE: libcamera_controls__bindgen_ty_1 = 41;
pub const AF_PAUSE_STATE: libcamera_controls__bindgen_ty_1 = 42;
pub const HDR_MODE: libcamera_controls__bindgen_ty_1 = 43;
pub const HDR_CHANNEL: libcamera_controls__bindgen_ty_1 = 44;
pub const GAMMA: libcamera_controls__bindgen_ty_1 = 45;
pub const DEBUG_METADATA_ENABLE: libcamera_controls__bindgen_ty_1 = 46;
pub const FRAME_WALL_CLOCK: libcamera_controls__bindgen_ty_1 = 47;
pub const WDR_MODE: libcamera_controls__bindgen_ty_1 = 48;
pub const WDR_STRENGTH: libcamera_controls__bindgen_ty_1 = 49;
pub const WDR_MAX_BRIGHT_PIXELS: libcamera_controls__bindgen_ty_1 = 50;
pub const LENS_DEWARP_ENABLE: libcamera_controls__bindgen_ty_1 = 51;
pub const LENS_SHADING_CORRECTION_ENABLE: libcamera_controls__bindgen_ty_1 = 52;
pub type libcamera_controls__bindgen_ty_1 = ::std::os::raw::c_uint;
pub const libcamera_controls_AeStateEnum_AeStateIdle: libcamera_controls_AeStateEnum = 0;
pub const libcamera_controls_AeStateEnum_AeStateSearching: libcamera_controls_AeStateEnum = 1;
pub const libcamera_controls_AeStateEnum_AeStateConverged: libcamera_controls_AeStateEnum = 2;
pub type libcamera_controls_AeStateEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AeMeteringModeEnum_MeteringCentreWeighted: libcamera_controls_AeMeteringModeEnum = 0;
pub const libcamera_controls_AeMeteringModeEnum_MeteringSpot: libcamera_controls_AeMeteringModeEnum = 1;
pub const libcamera_controls_AeMeteringModeEnum_MeteringMatrix: libcamera_controls_AeMeteringModeEnum = 2;
pub const libcamera_controls_AeMeteringModeEnum_MeteringCustom: libcamera_controls_AeMeteringModeEnum = 3;
pub type libcamera_controls_AeMeteringModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AeConstraintModeEnum_ConstraintNormal: libcamera_controls_AeConstraintModeEnum = 0;
pub const libcamera_controls_AeConstraintModeEnum_ConstraintHighlight: libcamera_controls_AeConstraintModeEnum = 1;
pub const libcamera_controls_AeConstraintModeEnum_ConstraintShadows: libcamera_controls_AeConstraintModeEnum = 2;
pub const libcamera_controls_AeConstraintModeEnum_ConstraintCustom: libcamera_controls_AeConstraintModeEnum = 3;
pub type libcamera_controls_AeConstraintModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AeExposureModeEnum_ExposureNormal: libcamera_controls_AeExposureModeEnum = 0;
pub const libcamera_controls_AeExposureModeEnum_ExposureShort: libcamera_controls_AeExposureModeEnum = 1;
pub const libcamera_controls_AeExposureModeEnum_ExposureLong: libcamera_controls_AeExposureModeEnum = 2;
pub const libcamera_controls_AeExposureModeEnum_ExposureCustom: libcamera_controls_AeExposureModeEnum = 3;
pub type libcamera_controls_AeExposureModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_ExposureTimeModeEnum_ExposureTimeModeAuto: libcamera_controls_ExposureTimeModeEnum = 0;
pub const libcamera_controls_ExposureTimeModeEnum_ExposureTimeModeManual: libcamera_controls_ExposureTimeModeEnum = 1;
pub type libcamera_controls_ExposureTimeModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AnalogueGainModeEnum_AnalogueGainModeAuto: libcamera_controls_AnalogueGainModeEnum = 0;
pub const libcamera_controls_AnalogueGainModeEnum_AnalogueGainModeManual: libcamera_controls_AnalogueGainModeEnum = 1;
pub type libcamera_controls_AnalogueGainModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AeFlickerModeEnum_FlickerOff: libcamera_controls_AeFlickerModeEnum = 0;
pub const libcamera_controls_AeFlickerModeEnum_FlickerManual: libcamera_controls_AeFlickerModeEnum = 1;
pub const libcamera_controls_AeFlickerModeEnum_FlickerAuto: libcamera_controls_AeFlickerModeEnum = 2;
pub type libcamera_controls_AeFlickerModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AwbModeEnum_AwbAuto: libcamera_controls_AwbModeEnum = 0;
pub const libcamera_controls_AwbModeEnum_AwbIncandescent: libcamera_controls_AwbModeEnum = 1;
pub const libcamera_controls_AwbModeEnum_AwbTungsten: libcamera_controls_AwbModeEnum = 2;
pub const libcamera_controls_AwbModeEnum_AwbFluorescent: libcamera_controls_AwbModeEnum = 3;
pub const libcamera_controls_AwbModeEnum_AwbIndoor: libcamera_controls_AwbModeEnum = 4;
pub const libcamera_controls_AwbModeEnum_AwbDaylight: libcamera_controls_AwbModeEnum = 5;
pub const libcamera_controls_AwbModeEnum_AwbCloudy: libcamera_controls_AwbModeEnum = 6;
pub const libcamera_controls_AwbModeEnum_AwbCustom: libcamera_controls_AwbModeEnum = 7;
pub type libcamera_controls_AwbModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AfModeEnum_AfModeManual: libcamera_controls_AfModeEnum = 0;
pub const libcamera_controls_AfModeEnum_AfModeAuto: libcamera_controls_AfModeEnum = 1;
pub const libcamera_controls_AfModeEnum_AfModeContinuous: libcamera_controls_AfModeEnum = 2;
pub type libcamera_controls_AfModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AfRangeEnum_AfRangeNormal: libcamera_controls_AfRangeEnum = 0;
pub const libcamera_controls_AfRangeEnum_AfRangeMacro: libcamera_controls_AfRangeEnum = 1;
pub const libcamera_controls_AfRangeEnum_AfRangeFull: libcamera_controls_AfRangeEnum = 2;
pub type libcamera_controls_AfRangeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AfSpeedEnum_AfSpeedNormal: libcamera_controls_AfSpeedEnum = 0;
pub const libcamera_controls_AfSpeedEnum_AfSpeedFast: libcamera_controls_AfSpeedEnum = 1;
pub type libcamera_controls_AfSpeedEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AfMeteringEnum_AfMeteringAuto: libcamera_controls_AfMeteringEnum = 0;
pub const libcamera_controls_AfMeteringEnum_AfMeteringWindows: libcamera_controls_AfMeteringEnum = 1;
pub type libcamera_controls_AfMeteringEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AfTriggerEnum_AfTriggerStart: libcamera_controls_AfTriggerEnum = 0;
pub const libcamera_controls_AfTriggerEnum_AfTriggerCancel: libcamera_controls_AfTriggerEnum = 1;
pub type libcamera_controls_AfTriggerEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AfPauseEnum_AfPauseImmediate: libcamera_controls_AfPauseEnum = 0;
pub const libcamera_controls_AfPauseEnum_AfPauseDeferred: libcamera_controls_AfPauseEnum = 1;
pub const libcamera_controls_AfPauseEnum_AfPauseResume: libcamera_controls_AfPauseEnum = 2;
pub type libcamera_controls_AfPauseEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AfStateEnum_AfStateIdle: libcamera_controls_AfStateEnum = 0;
pub const libcamera_controls_AfStateEnum_AfStateScanning: libcamera_controls_AfStateEnum = 1;
pub const libcamera_controls_AfStateEnum_AfStateFocused: libcamera_controls_AfStateEnum = 2;
pub const libcamera_controls_AfStateEnum_AfStateFailed: libcamera_controls_AfStateEnum = 3;
pub type libcamera_controls_AfStateEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_AfPauseStateEnum_AfPauseStateRunning: libcamera_controls_AfPauseStateEnum = 0;
pub const libcamera_controls_AfPauseStateEnum_AfPauseStatePausing: libcamera_controls_AfPauseStateEnum = 1;
pub const libcamera_controls_AfPauseStateEnum_AfPauseStatePaused: libcamera_controls_AfPauseStateEnum = 2;
pub type libcamera_controls_AfPauseStateEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_HdrModeEnum_HdrModeOff: libcamera_controls_HdrModeEnum = 0;
pub const libcamera_controls_HdrModeEnum_HdrModeMultiExposureUnmerged: libcamera_controls_HdrModeEnum = 1;
pub const libcamera_controls_HdrModeEnum_HdrModeMultiExposure: libcamera_controls_HdrModeEnum = 2;
pub const libcamera_controls_HdrModeEnum_HdrModeSingleExposure: libcamera_controls_HdrModeEnum = 3;
pub const libcamera_controls_HdrModeEnum_HdrModeNight: libcamera_controls_HdrModeEnum = 4;
pub type libcamera_controls_HdrModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_HdrChannelEnum_HdrChannelNone: libcamera_controls_HdrChannelEnum = 0;
pub const libcamera_controls_HdrChannelEnum_HdrChannelShort: libcamera_controls_HdrChannelEnum = 1;
pub const libcamera_controls_HdrChannelEnum_HdrChannelMedium: libcamera_controls_HdrChannelEnum = 2;
pub const libcamera_controls_HdrChannelEnum_HdrChannelLong: libcamera_controls_HdrChannelEnum = 3;
pub type libcamera_controls_HdrChannelEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_WdrModeEnum_WdrOff: libcamera_controls_WdrModeEnum = 0;
pub const libcamera_controls_WdrModeEnum_WdrLinear: libcamera_controls_WdrModeEnum = 1;
pub const libcamera_controls_WdrModeEnum_WdrPower: libcamera_controls_WdrModeEnum = 2;
pub const libcamera_controls_WdrModeEnum_WdrExponential: libcamera_controls_WdrModeEnum = 3;
pub const libcamera_controls_WdrModeEnum_WdrHistogramEqualization: libcamera_controls_WdrModeEnum = 4;
pub type libcamera_controls_WdrModeEnum = ::std::os::raw::c_uint;
pub const AE_PRECAPTURE_TRIGGER: libcamera_controls_draft__bindgen_ty_1 = 10001;
pub const NOISE_REDUCTION_MODE: libcamera_controls_draft__bindgen_ty_1 = 10002;
pub const COLOR_CORRECTION_ABERRATION_MODE: libcamera_controls_draft__bindgen_ty_1 = 10003;
pub const AWB_STATE: libcamera_controls_draft__bindgen_ty_1 = 10004;
pub const SENSOR_ROLLING_SHUTTER_SKEW: libcamera_controls_draft__bindgen_ty_1 = 10005;
pub const LENS_SHADING_MAP_MODE: libcamera_controls_draft__bindgen_ty_1 = 10006;
pub const PIPELINE_DEPTH: libcamera_controls_draft__bindgen_ty_1 = 10007;
pub const MAX_LATENCY: libcamera_controls_draft__bindgen_ty_1 = 10008;
pub const TEST_PATTERN_MODE: libcamera_controls_draft__bindgen_ty_1 = 10009;
pub const FACE_DETECT_MODE: libcamera_controls_draft__bindgen_ty_1 = 10010;
pub const FACE_DETECT_FACE_RECTANGLES: libcamera_controls_draft__bindgen_ty_1 = 10011;
pub const FACE_DETECT_FACE_SCORES: libcamera_controls_draft__bindgen_ty_1 = 10012;
pub const FACE_DETECT_FACE_LANDMARKS: libcamera_controls_draft__bindgen_ty_1 = 10013;
pub const FACE_DETECT_FACE_IDS: libcamera_controls_draft__bindgen_ty_1 = 10014;
pub type libcamera_controls_draft__bindgen_ty_1 = ::std::os::raw::c_uint;
pub const libcamera_controls_draft_AePrecaptureTriggerEnum_AePrecaptureTriggerIdle:
    libcamera_controls_draft_AePrecaptureTriggerEnum = 0;
pub const libcamera_controls_draft_AePrecaptureTriggerEnum_AePrecaptureTriggerStart:
    libcamera_controls_draft_AePrecaptureTriggerEnum = 1;
pub const libcamera_controls_draft_AePrecaptureTriggerEnum_AePrecaptureTriggerCancel:
    libcamera_controls_draft_AePrecaptureTriggerEnum = 2;
pub type libcamera_controls_draft_AePrecaptureTriggerEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_draft_NoiseReductionModeEnum_NoiseReductionModeOff:
    libcamera_controls_draft_NoiseReductionModeEnum = 0;
pub const libcamera_controls_draft_NoiseReductionModeEnum_NoiseReductionModeFast:
    libcamera_controls_draft_NoiseReductionModeEnum = 1;
pub const libcamera_controls_draft_NoiseReductionModeEnum_NoiseReductionModeHighQuality:
    libcamera_controls_draft_NoiseReductionModeEnum = 2;
pub const libcamera_controls_draft_NoiseReductionModeEnum_NoiseReductionModeMinimal:
    libcamera_controls_draft_NoiseReductionModeEnum = 3;
pub const libcamera_controls_draft_NoiseReductionModeEnum_NoiseReductionModeZSL:
    libcamera_controls_draft_NoiseReductionModeEnum = 4;
pub type libcamera_controls_draft_NoiseReductionModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_draft_ColorCorrectionAberrationModeEnum_ColorCorrectionAberrationOff:
    libcamera_controls_draft_ColorCorrectionAberrationModeEnum = 0;
pub const libcamera_controls_draft_ColorCorrectionAberrationModeEnum_ColorCorrectionAberrationFast:
    libcamera_controls_draft_ColorCorrectionAberrationModeEnum = 1;
pub const libcamera_controls_draft_ColorCorrectionAberrationModeEnum_ColorCorrectionAberrationHighQuality:
    libcamera_controls_draft_ColorCorrectionAberrationModeEnum = 2;
pub type libcamera_controls_draft_ColorCorrectionAberrationModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_draft_AwbStateEnum_AwbStateInactive: libcamera_controls_draft_AwbStateEnum = 0;
pub const libcamera_controls_draft_AwbStateEnum_AwbStateSearching: libcamera_controls_draft_AwbStateEnum = 1;
pub const libcamera_controls_draft_AwbStateEnum_AwbConverged: libcamera_controls_draft_AwbStateEnum = 2;
pub const libcamera_controls_draft_AwbStateEnum_AwbLocked: libcamera_controls_draft_AwbStateEnum = 3;
pub type libcamera_controls_draft_AwbStateEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_draft_LensShadingMapModeEnum_LensShadingMapModeOff:
    libcamera_controls_draft_LensShadingMapModeEnum = 0;
pub const libcamera_controls_draft_LensShadingMapModeEnum_LensShadingMapModeOn:
    libcamera_controls_draft_LensShadingMapModeEnum = 1;
pub type libcamera_controls_draft_LensShadingMapModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_draft_TestPatternModeEnum_TestPatternModeOff:
    libcamera_controls_draft_TestPatternModeEnum = 0;
pub const libcamera_controls_draft_TestPatternModeEnum_TestPatternModeSolidColor:
    libcamera_controls_draft_TestPatternModeEnum = 1;
pub const libcamera_controls_draft_TestPatternModeEnum_TestPatternModeColorBars:
    libcamera_controls_draft_TestPatternModeEnum = 2;
pub const libcamera_controls_draft_TestPatternModeEnum_TestPatternModeColorBarsFadeToGray:
    libcamera_controls_draft_TestPatternModeEnum = 3;
pub const libcamera_controls_draft_TestPatternModeEnum_TestPatternModePn9:
    libcamera_controls_draft_TestPatternModeEnum = 4;
pub const libcamera_controls_draft_TestPatternModeEnum_TestPatternModeCustom1:
    libcamera_controls_draft_TestPatternModeEnum = 256;
pub type libcamera_controls_draft_TestPatternModeEnum = ::std::os::raw::c_uint;
pub const libcamera_controls_draft_FaceDetectModeEnum_FaceDetectModeOff: libcamera_controls_draft_FaceDetectModeEnum =
    0;
pub const libcamera_controls_draft_FaceDetectModeEnum_FaceDetectModeSimple:
    libcamera_controls_draft_FaceDetectModeEnum = 1;
pub const libcamera_controls_draft_FaceDetectModeEnum_FaceDetectModeFull: libcamera_controls_draft_FaceDetectModeEnum =
    2;
pub type libcamera_controls_draft_FaceDetectModeEnum = ::std::os::raw::c_uint;
pub const LOCATION: libcamera_properties__bindgen_ty_1 = 1;
pub const ROTATION: libcamera_properties__bindgen_ty_1 = 2;
pub const MODEL: libcamera_properties__bindgen_ty_1 = 3;
pub const UNIT_CELL_SIZE: libcamera_properties__bindgen_ty_1 = 4;
pub const PIXEL_ARRAY_SIZE: libcamera_properties__bindgen_ty_1 = 5;
pub const PIXEL_ARRAY_OPTICAL_BLACK_RECTANGLES: libcamera_properties__bindgen_ty_1 = 6;
pub const PIXEL_ARRAY_ACTIVE_AREAS: libcamera_properties__bindgen_ty_1 = 7;
pub const SCALER_CROP_MAXIMUM: libcamera_properties__bindgen_ty_1 = 8;
pub const SENSOR_SENSITIVITY: libcamera_properties__bindgen_ty_1 = 9;
pub const SYSTEM_DEVICES: libcamera_properties__bindgen_ty_1 = 10;
pub type libcamera_properties__bindgen_ty_1 = ::std::os::raw::c_uint;
pub const libcamera_properties_LocationEnum_CameraLocationFront: libcamera_properties_LocationEnum = 0;
pub const libcamera_properties_LocationEnum_CameraLocationBack: libcamera_properties_LocationEnum = 1;
pub const libcamera_properties_LocationEnum_CameraLocationExternal: libcamera_properties_LocationEnum = 2;
pub type libcamera_properties_LocationEnum = ::std::os::raw::c_uint;
pub const COLOR_FILTER_ARRANGEMENT: libcamera_properties_draft__bindgen_ty_1 = 10001;
pub type libcamera_properties_draft__bindgen_ty_1 = ::std::os::raw::c_uint;
pub const libcamera_properties_draft_ColorFilterArrangementEnum_RGGB:
    libcamera_properties_draft_ColorFilterArrangementEnum = 0;
pub const libcamera_properties_draft_ColorFilterArrangementEnum_GRBG:
    libcamera_properties_draft_ColorFilterArrangementEnum = 1;
pub const libcamera_properties_draft_ColorFilterArrangementEnum_GBRG:
    libcamera_properties_draft_ColorFilterArrangementEnum = 2;
pub const libcamera_properties_draft_ColorFilterArrangementEnum_BGGR:
    libcamera_properties_draft_ColorFilterArrangementEnum = 3;
pub const libcamera_properties_draft_ColorFilterArrangementEnum_RGB:
    libcamera_properties_draft_ColorFilterArrangementEnum = 4;
pub const libcamera_properties_draft_ColorFilterArrangementEnum_MONO:
    libcamera_properties_draft_ColorFilterArrangementEnum = 5;
pub type libcamera_properties_draft_ColorFilterArrangementEnum = ::std::os::raw::c_uint;
